# Generated by Django 4.2.6 on 2023-10-06 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric_global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('total_number_of_objects', models.PositiveIntegerField()),
                ('average_loading_time_global', models.FloatField()),
                ('number_of_views_global', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create_local', models.DateTimeField()),
                ('number_of_edit_local', models.PositiveIntegerField()),
                ('number_of_views_local', models.PositiveIntegerField()),
                ('average_loading_time_local', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metric_global')),
            ],
        ),
        migrations.DeleteModel(
            name='data_test',
        ),
    ]
