# Generated by Django 4.2.6 on 2023-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metric_global_metric_local_delete_data_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('event_time', models.DateTimeField()),
                ('project_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='metric_local',
            name='metric',
        ),
        migrations.DeleteModel(
            name='Metric_global',
        ),
        migrations.DeleteModel(
            name='Metric_local',
        ),
    ]
