<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_notes_delete_metric_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('event_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
=======
# Generated by Django 4.2.6 on 2023-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_notes_delete_metric_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('event_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
>>>>>>> a889ceef976b48a8b5401e1b239215bbc3ee6862
